In [4]:
import numpy as np

In [5]:
npy_file_path = "_cache/sample_train.npy"

In [6]:
npy_data = np.load(npy_file_path)

In [7]:
print("Shape of the data:", npy_data.shape)
print("Data type:", npy_data.dtype)


Shape of the data: (755, 7, 5000)
Data type: float64


In [8]:
print(" rows_X:")
print(npy_data[1:5])


 rows_X:
[[[ 9.260e-01  5.440e-01  7.800e-01 ...  2.028e+00  2.195e+00 -3.340e-01]
  [ 2.950e-01  4.790e-01 -5.300e-02 ...  6.358e+00  3.035e+00  2.151e+00]
  [ 9.790e-01  2.720e-01 -1.387e+00 ... -8.210e-01  4.613e+00 -1.597e+00]
  ...
  [-7.600e-02  3.700e-02 -2.900e-02 ... -7.000e-02 -2.200e-02  3.300e-02]
  [-1.160e-01  3.600e-02 -3.500e-02 ... -1.150e-01 -7.400e-02  4.000e-03]
  [-5.000e-03 -5.000e-03 -5.000e-03 ...  1.830e-01  1.720e-01  1.620e-01]]

 [[ 9.960e-01  1.327e+00  1.157e+00 ...  1.555e+00  4.226e+00  2.045e+00]
  [ 1.102e+00  1.197e+00  1.523e+00 ...  2.713e+00  1.860e+00  1.089e+00]
  [ 7.570e-01  8.100e-02 -9.270e-01 ...  2.460e+00 -1.157e+00  1.951e+00]
  ...
  [-7.100e-02 -2.000e-03 -3.300e-02 ... -5.600e-02  3.900e-02 -9.300e-02]
  [-6.500e-02  5.000e-03 -6.000e-02 ... -5.300e-02 -1.200e-02 -8.100e-02]
  [-5.000e-03 -4.000e-03 -2.000e-03 ...  2.390e-01  2.290e-01  2.090e-01]]

 [[ 6.340e-01  4.900e-01  5.020e-01 ...  1.859e+00  4.377e+00  3.656e+00]
  [ 2.005e+00